name: Daily Commit

on:
  schedule:
    - cron: '15 4 * * *'  # Runs daily at 04:15 UTC
  workflow_dispatch:       # Allows manual trigger via GitHub UI

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit step - 23f3003822@ds.study.iitm.ac.in
        run: |
          echo "Daily log entry at $(date -u)" >> daily-log.txt

      - name: Git Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Auto daily commit at $(date -u)" || echo "No changes to commit"
          git push
